apiVersion: v1
kind: Service

metadata:
  name: utility-chatbot-service

spec:
  selector:
    app: utility-chatbot

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: NodePort
